UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3
PICKUP = 4
DELIVER = 5
RECHARGE = 6

ACTIONS = [UP, DOWN, LEFT, RIGHT, PICKUP, DELIVER, RECHARGE]

ACTION_TO_DELTA = {
    UP: (-1, 0),
    DOWN: (1, 0),
    LEFT: (0, -1),
    RIGHT: (0, 1),
    PICKUP: (0, 0),
    DELIVER: (0, 0),
    RECHARGE: (0, 0),
}